// export const ADD_TODO = "ADD_TODO";
// export const TOGGLE_TODO = "TOGGLE_TODO";
// export const SET_FILTER = "SET_FILTER";
export const FETCH_SHIPMENTS = "FETCH_SHIPMENTS";
export const UPDATE_SHIPMENTS = "UPDATE_SHIPMENTS";
export const INIT_SHIPMENTS = "INIT_SHIPMENTS";
export const UPDATE_PAGE_NUMBER = "UPDATE_PAGE_NUMBER";
export const SEARCH_SHIPMENT = "SEARCH_SHIPMENT";
export const CLEAR_SEARCH = "CLEAR_SEARCH";

export const SORT_SHIPMENT = "SORT_SHIPMENT"
